### ISSUE TITLE
API example from docs not working?

### ISSUE THREAD

**Issue by michielbdejong** [m-ld/timeld#106]
Following the instructions from https://github.com/m-ld/timeld/blob/main/doc/api.md#import I see:

```
curl -X POST -d @./example.ndjson  -u $CREDENTIALS -H 'Content-Type: appon/x-ndjson' https://timeld.org/api/import
{"code":"InternalServer","message":"caused by Error: Could not parse row {\"@type\":\"Project\",\"@id\":\"org1/pr1\",\"external\":{\"@..."}
```

Did the API change or am I doing something wrong in my curl command?

This is the contents of example.ndjson:
```
cat example.ndjson 
{"@type":"Project","@id":"org1/pr1","external":{"@id":"http://ex.org/project/1"}}
{"@type":"Timesheet","@id":"org1/ts1","project":[{"@id":"org1/pr1"}],"external":{"@id":"http://ex.org/timesheet/1"}}
{"@type":"Entry","session":{"@id":"org1/ts1"},"activity":"orging","duration":60,"start":{"@value":"2022-06-22T16:40:55.946Z","@type":"http://www.w3.org/2001/XMLSchema#dateTime"},"vf:provider":{"@id":"test"},"external":{"@id":"http://ex.org/timesheet/1/entry/1"}}
```

**Comment by mcalligator** [comment]
Could you describe the setup you're using to do this?  Is it straight from the GitHub repo, from the test suite that Yvo created, or the Docker images?  That would help with reproducing the issue :-).

**Comment by michielbdejong** [comment]
This is testing against your production server, note that the URL is https://timeld.org/api/import
You can just run this curl command as-is from any internet-connected machine, just make sure you set the `$CREDENTIALS` env var to `<your-user>` + `:` + `<your-key>`

**Comment by gsvarovsky** [comment]
Please can you try using [--data-binary](https://curl.se/docs/manpage.html#--data-binary)?

> [When -d, --data is told to read from a file like that, carriage returns and newlines will be stripped out.](https://curl.se/docs/manpage.html#-d)

**Comment by michielbdejong** [comment]
Ah. that helps! Added this in https://github.com/m-ld/timeld/pull/107

But I'm still getting `{"code":"Forbidden","message":""}` as the response. That is probably because I need to replace  the strings `"org1/pr1"` and `"org1/ts1"`. How do I know which values to put in there?

**Comment by michielbdejong** [comment]
Ah, I think I found mine - `"fedb/fedt"` and `"fedb/from-ponder-source-testing"`, with the following I get a 200 response:
```
{"@type":"Project","@id":"fedb/fedt","external":{"@id":"http://ex.org/project/1"}}
{"@type":"Timesheet","@id":"fedb/from-ponder-source-testing","project":[{"@id":"fedb/fedt"}],"external":{"@id":"http://ex.org/timesheet/1"}}
{"@type":"Entry","session":{"@id":"fedb/from-ponder-source-testing"},"activity":"orging","duration":60,"start":{"@value":"2022-06-22T16:40:55.946Z","@type":"http://www.w3.org/2001/XMLSchema#dateTime"},"vf:provider":{"@id":"test"},"external":{"@id":"http://ex.org/timesheet/1/entry/1"}}
```
