### ISSUE TITLE
Debugging my cli+gateway setup

### ISSUE THREAD

**Issue by michielbdejong** [m-ld/timeld#38]
I set up the gateway on fly.io + Ably + Courier
I got the cli app running on my laptop.
The emails don't arrive but I can see them in the Courier logs so at least I was able to get the activation code.
After that, the `timeld open my-timesheet` command took a long time and then finally printed:
```
Fetch from https://frosty-hill-2761.fly.dev/api/key/michiel failed with 500: Internal Server Error
```

On https://fly.io/apps/frosty-hill-2761/monitoring I only see
```
2022-07-06T07:59:52.894 app[76391911] lhr [info] restify listening at http://[::]:8080
```
as the last log entry, so that's not helpful.
IIUC fly.io is heroku under the hood, so I would expect error messages about 500 errors to show up in the application log?

**Comment by michielbdejong** [comment]
Ah, `flyctl logs`.

**Comment by michielbdejong** [comment]
Hm, now when I try `timeld open my-timesheet` again it says:
```
Please enter your email address to register this device: michiel@pondersource.com
```
again (probably because the first time it resulted in a 500?) but then it doesn't continue to "Check your email and paste the code", but instead immediately prints:
```
Fetch from https://frosty-hill-2761.fly.dev/api/jwe/michiel?email=michiel%40pondersource.com failed with 401: Unauthorized
```

**Comment by michielbdejong** [comment]
Ah, worked around that by using `timeld -u test open my-timesheet`.

**Comment by michielbdejong** [comment]
Hm, as expected that lead to:
```
Fetch from https://frosty-hill-2761.fly.dev/api/key/test failed with 500: Internal Server Error
```
But unfortunately no errors were logged in `flyctl logs`.

**Comment by gsvarovsky** [comment]
Addressed error handling in 
https://github.com/m-ld/timeld/tree/42-server-error-reporting
&
https://www.npmjs.com/package/timeld-gateway/v/0.2.2-0

I have not yet tried the fresh deploy, so no problem if you don't have time to test it.

**Comment by Angus-McAllister** [comment]
> Addressed error handling in
> https://github.com/m-ld/timeld/tree/42-server-error-reporting

That first link appears to be broken.  A quick search of the repo in case it had been moved revealed no similar content, hence it's either been renamed or deleted entirely.  Could you update the link accordingly?

**Comment by gsvarovsky** [comment]
Closing as stale
