### ISSUE TITLE
Have a problem with import

### ISSUE THREAD

**Issue by ishifoev** [m-ld/timeld#49]
When I would like import any information to your system 403 forbidden, is it any ACL in your system @gsvarovsky @Angus-McAllister

**Comment by gsvarovsky** [comment]
Hi Ismoil! I can see in the logs that you are using a key starting with `ismoil:DLmpbQ.`.

Please can you drop the `ismoil:`, so that the key starts with just `DLmpbQ.`

Maybe you have fixed this already, in that case, please can you attach your full cURL details? Thanks

**Comment by ishifoev** [comment]
```curl  -H "Content-Type:  application/x-ndjson" -d '{"@type":"Timesheet","@id":"org1/ts1","project":[{"@id":"org1/pr1"}],"external":{"@id":"http://ex.org/timesheet/1"}}' -u ismoil:DLmpbQ.msd0Lw:wDkrDp98D4bCdeCyyIOwUEW6jGdP-adNCMxLj2sO4cs https://timeld.org/api/import```

**Comment by ishifoev** [comment]
without starting ismoil give another error

```
code":"Unauthorized","message":"Bad user DLmpbQ.msd0L
```

**Comment by gsvarovsky** [comment]
Yes, there is an ACL. You are not an owner of the organisation account `org1` so you cannot add to it.

For now you can import data with your own user account: (timesheet ID starts with "ismoil/")

```
curl -H "Content-Type: application/x-ndjson" -d '{"@type":"Timesheet","@id":"ismoil/ts1","project":[],"external":{"@id":"http://ex.org/timesheet/1"}}' -u ismoil:DLmpbQ.msd0Lw:*** https://timeld.org/api/import
```

If you want to create a new organisation, you can use the timeld CLI to create it first.

**Comment by ishifoev** [comment]
@gsvarovsky Thank you for provide information. But for now it is not respond anything. When for example import successfully add, any message will be back or not?

**Comment by gsvarovsky** [comment]
Nothing is good! curl outputs only the response body by default, and there is no response body in case of success for a POST request. You can get curl to output the response headers & status code with [--include](https://curl.se/docs/manpage.html#-i)

You can also check that your timesheet now exists using the [report API](https://github.com/m-ld/timeld/blob/main/doc/api.md#report)

**Comment by ishifoev** [comment]
@gsvarovsky  Thank you, I see it is working now, I will close this issue)
