### ISSUE TITLE
Not possible to modify date of a timesheet entry

### ISSUE THREAD

**Issue by Angus-McAllister** [m-ld/timeld#51]
Although one can modify a timesheet entry, this extends only to its duration.  It needs to be possible to change the following additional properties of the entry as well:

- `Date`;
- `Start time`; and
- `Description`.

**Comment by gsvarovsky** [comment]
You should be able to edit the start time with the `modify ".." --start <time>`. Not working?

That also modifies the start date e.g. `modify ".." --start yesterday 10am`.

Description – yep, not available. Also missing is removing an entry! – if that were available you could just delete and re-create.

**Comment by Angus-McAllister** [comment]
Confirmed that it's possible to `modify ".." --start <time>`.  The confusion arose because `duration` is a positional argument, whereas `start` and `end` are options.  The latter two aren't shown in response to entering `help` when in a timesheet session, but only at the next level down of `modify --help`.
