### ISSUE TITLE
API import not returning create IDs and not supporting updates

### ISSUE THREAD

**Issue by kroky** [m-ld/timeld#57]
I need to map the created timesheet entry IDs from timeld to my timesheet entries locally, so I know I don't send them again for import. Can import endpoint return created entry IDs?

Also, if I don't have the IDs of the entries, I can't send update requests. I know the API doesn't support updates for now but probably a future extension would do it? Both prejorunal and Tiki support timesheet entry updates via the API.

**Comment by gsvarovsky** [comment]
Every imported JSON object is treated as an **overwrite**. So you can update an entry by sending its information again with some change.

For timesheet entries, you must include an `external` property which is the identifier in _your_ system. **If you send the same identifier again, it will overwrite the previous entry information.** So, there's no need for you to know our internal ID.

(For Timesheets and Projects, you have to specify the `@id` anyway.)

**Comment by kroky** [comment]
I see. Then, we are all set here.
