### ISSUE TITLE
`report <project-name>` fails with 500 error

### ISSUE THREAD

**Issue by Angus-McAllister** [m-ld/timeld#60]
In a timeld-cli admin session, the command `report "<Valid Project>"` consistently results in the following error (after a delay of ~30s):

`Fetch from https://timeld.org/api/rpt/<user>/own/Valid%20Project?user=<user> failed with 500: Internal Server Error`

(Note that actual project name and user have been de-identified for confidentiality reasons).

**Comment by gsvarovsky** [comment]
Likely to be the same as #59 (possibly with a different character-match problem). DM me the failing IDs pls.

**Comment by Angus-McAllister** [comment]
Done.  Concerning the possible common underlying cause with #59, the Timesheet name in the above case is in fact all lower-case, but the Project name has some upper-case characters.  If it's the same code that handles the latter entity class, then it's likely to be that.  Could that restriction be relaxed?  Some people prefer the flexibility of being able to use upper-case characters in entity names.

**Comment by gsvarovsky** [comment]
Decided in update meeting 15-Aug-22 not to change this restriction.

https://gitter.im/federatedbookkeeping/timesheets?at=62fa2c04443b7927a76ce94d
