### ISSUE TITLE
add integration command fails with 500: Internal Server Error

### ISSUE THREAD

**Issue by Angus-McAllister** [m-ld/timeld#78]
Context: `timeld admin` REPL

When attempting to create an integration of a given timesheet with other time-tracking tools, the command  `add integration --ts <integration-module> <timesheet-name>` , the request fails with a 500 Internal Server Error - *if* an invalid `integration module` argument is used.  (It succeeds with a valid argument).

**Comment by gsvarovsky** [comment]
Fixed in https://github.com/m-ld/timeld/commit/8fcb47d544899c787b9a326396290413cfae9023
