### ISSUE TITLE
Update Containerised deployment to generate keys

### ISSUE THREAD

**Issue by mcalligator** [m-ld/timeld#98]
Current containerised deployment uses manually-created `TIMELD_GATEWAY_AUTH__KEY`; forthcoming release (in [edge](https://github.com/m-ld/timeld/tree/edge) branch) generates 3 keys that need to be included in the .env deployment file.

This task is to create the updated Docker container for timeld Gateway that uses the new approach to admin key management.  This involves the following two steps:
1. Generate a new `.env` file automatically, incorporating the [existing key-gen script](https://github.com/m-ld/timeld/blob/edge/packages/gateway/genkey.mjs
); and
2. Updating the Docker image build to use the code in GitHub as its source.

**Comment by gsvarovsky** [comment]
Fixed in https://github.com/m-ld/timeld/pull/50/commits/c92ff5a9e5515121fa50c4d14f714e0e2369089f
